### ISSUE TITLE
Add new printer on ET series

### ISSUE THREAD

**Issue by MWMatthieuBR** [Ircama/epson_print_conf#26]
Hello,
First of all thank you for your program, you saved one of my 2 printers !!!
I followed your instructions to add a new printer with the link on Codeberg, because my first printer is an ET-2756 but the second is an ET-2856 and it is not in your program.

The command only gives me parameters on ET-2851 ET-2853 ET-2855 for the 2850 series, I tried to reset the counter with that but it doesn't work, when I restart my printer I get error E-11.

Can you help me to understand why ? Thank you !

**Comment by MWMatthieuBR** [comment]
Hello, i view your commit and git reset to have it.
The config given by codeberg is :
````JSON
 "ET-2850": {
            "alias": ["ET-2853", "ET-2855", "ET-2851"],
            "read_key": [74, 54],
            "write_key": b'Arantifo',
            "main_waste": {"oids": [48, 49, 47], "divider": 109.13},
            "borderless_waste": {"oids": [50, 51, 47], "divider": 16.31},
            "third_waste": {"oids": [252, 253, 254], "divider": 15.3},
            "raw_waste_reset": {
                48: 0, 49: 0, 47: 0, 52: 0, 53: 0, 54: 94, 50: 0,
                51: 0, 55: 94, 28: 0, 252: 0, 253: 0, 254: 0, 255: 94
            },
            "stats": {
                "Total print pass counter": [133, 132, 131, 130],
                "Total print page counter - rear": [755, 754, 753, 752],
                "Total print page counter - duplex": [763, 762, 761, 760],
                "Total scan counter": [1843, 1842, 1841, 1840],
                "Ink replacement counter %-- Black": [554],
                "Ink replacement counter %-- Cyan": [555],
                "Ink replacement counter %-- Magenta": [556],
                "Ink replacement counter %-- Yellow": [557]
            },
            "serial_number": range(1604, 1614),
        }
     
 ````
 But with the new code I get an error because he received none for the values :
    [ERROR] int() can't convert non-string with explicit base
Traceback (most recent call last):
  File "C:\Users\***\Desktop\epson_print_conf\ui.py", line 678, in get_current_eeprom_values
    org_values = ', '.join(
                 
  File "C:\Users\***\Desktop\epson_print_conf\ui.py", line 679, in <genexpr>
    f"{k}: {int(v, 16)}" for k, v in zip(
          
TypeError: int() can't convert non-string with explicit base
````

[NOTE] Current EEPROM values for Raw waste reset: 48: None.
[NOTE] Current EEPROM values for Main waste reset: 48: None.
[NOTE] Current EEPROM values for Borderless waste reset: 50: None.

**Comment by Ircama** [comment]
> But with the new code I get an error because he received none for the values :

This is because you are using a wrong printer model, with a different "read_key" or "write_key" than the interfaced printer and the SNMP requests fail. Now appropriate error messages are produced instead of the Traceback.

**Comment by MWMatthieuBR** [comment]
I test with your new version of the project and your answer is good i don't have the good read_key :
ex : 
````DEBUG:root:EEPROM_DUMP Maintenance required level of 1st waste ink counter:
  ADDRESS: 1.3.6.1.4.1.1248.1.2.2.44.1.1.2.1.124.124.7.0.74.54.65.190.160.54.0
  OID: 54=0x36
DEBUG:root:  TAG: OctetString
  RESPONSE: b'\x00||:41:NA;\x0c'
INFO:root:Invalid read key.
````

But i don't know how to get it. Do you know how ? thanks !

**Comment by Ircama** [comment]
> But i don't know how to get it. Do you know how ? thanks !

Version 3 includes the "Detect Access Keys" button, which attempts to discover the *read_key* and *write_key* of the printer.

**Comment by PUN-app** [comment]
For the ET 2850 using v5.1(IP present but hidden with `x`)...
[INFO] Detecting printers... (this might take a while)
[INFO] Found printer 'EPSON ET-2850 Series' at x.x.x.x (hostname: Unknown)
[ERROR] Printer model unknown.
[INFO] Starting the access key detection, please wait for many minutes...
[INFO] Detecting the read_key...
[ERROR] Could not detect read_key.

**Comment by MWMatthieuBR** [comment]
Same as @PUN-app using the last version, can't detect the read_key..

**Comment by nannys-hedgehog** [comment]
@Ircama  I'm just here to report success on an Epson ET-2825, which is the same modell as ET-2820. Thank you for all the effort you took into this project.
To get it working with the ET-2825 I had first to FW downgrade the printer to FW XE18MB from XE120B via WicResetUtility, since FW XE120B does not support EEPROM access via WIFI but FW XE18MB does. Got the printer definitions imported into epson_print_conf from [Codeberg](https://codeberg.org/atufi/reinkpy) via toml file.

Actually I did reset it at first via Linux and the https://codeberg.org/atufi/reinkpy project. Afterwards I got carried away and explored if it isn't possible via epson_print_conf too (I'm running it on a Win7 machine) and found the solution via firmware downgrade. The WicResetUtility I used was version 5.90.

**Comment by mikuhl-dev** [comment]
For ET-2850 I used WIC Reset Utility to install firmware (there was only one version available), which allowed me to reset the waste ink levels after loading the TOML from https://codeberg.org/atufi/reinkpy/raw/branch/main/reinkpy/epson.toml. Printer was plugged in with USB, not sure if that made a difference.

**Comment by mmbarkel-cpu** [comment]
Used v7.0 but it it said printer model unknown (L3251)... it could not reset.. PLEASE HELP

**Comment by tycho-kirchner** [comment]
For ET-2820 I just added detailed instructions in the corresponding issue https://github.com/Ircama/epson_print_conf/issues/79

Thanks, Tycho

**Comment by Ircama** [comment]
Version 8.0.0 introduces preliminary USB support.
